// <auto-generated />
namespace Escape.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedUsrName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedUsrName));
        
        string IMigrationMetadata.Id
        {
            get { return "202107021838116_addedUsrName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
